//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: map.proto
namespace protocol.map
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"map_data")]
  public partial class map_data : global::ProtoBuf.IExtensible
  {
    public map_data() {}
    
    private int _map_ver;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"map_ver", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int map_ver
    {
      get { return _map_ver; }
      set { _map_ver = value; }
    }
    private byte[] _array;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"array", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public byte[] array
    {
      get { return _array; }
      set { _array = value; }
    }
    private int _x_num;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"x_num", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int x_num
    {
      get { return _x_num; }
      set { _x_num = value; }
    }
    private int _y_num;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"y_num", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int y_num
    {
      get { return _y_num; }
      set { _y_num = value; }
    }
    private int _qd_y;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"qd_y", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int qd_y
    {
      get { return _qd_y; }
      set { _qd_y = value; }
    }
    private int _zd_y;
    [global::ProtoBuf.ProtoMember(6, IsRequired = true, Name=@"zd_y", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int zd_y
    {
      get { return _zd_y; }
      set { _zd_y = value; }
    }
    private int _mode;
    [global::ProtoBuf.ProtoMember(7, IsRequired = true, Name=@"mode", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int mode
    {
      get { return _mode; }
      set { _mode = value; }
    }
    private int _time;
    [global::ProtoBuf.ProtoMember(8, IsRequired = true, Name=@"time", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int time
    {
      get { return _time; }
      set { _time = value; }
    }
    private int _map_theme;
    [global::ProtoBuf.ProtoMember(9, IsRequired = true, Name=@"map_theme", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int map_theme
    {
      get { return _map_theme; }
      set { _map_theme = value; }
    }
    private int _no_music;
    [global::ProtoBuf.ProtoMember(10, IsRequired = true, Name=@"no_music", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int no_music
    {
      get { return _no_music; }
      set { _no_music = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"map_url")]
  public partial class map_url : global::ProtoBuf.IExtensible
  {
    public map_url() {}
    
    private int _map_theme;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"map_theme", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int map_theme
    {
      get { return _map_theme; }
      set { _map_theme = value; }
    }
    private byte[] _array;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"array", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public byte[] array
    {
      get { return _array; }
      set { _array = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"map_data_sub")]
  public partial class map_data_sub : global::ProtoBuf.IExtensible
  {
    public map_data_sub() {}
    
    private byte[] _array;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"array", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public byte[] array
    {
      get { return _array; }
      set { _array = value; }
    }
    private int _x_num;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"x_num", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int x_num
    {
      get { return _x_num; }
      set { _x_num = value; }
    }
    private int _y_num;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"y_num", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int y_num
    {
      get { return _y_num; }
      set { _y_num = value; }
    }
    private int _qd_y;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"qd_y", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int qd_y
    {
      get { return _qd_y; }
      set { _qd_y = value; }
    }
    private int _zd_y;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"zd_y", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int zd_y
    {
      get { return _zd_y; }
      set { _zd_y = value; }
    }
    private int _map_theme;
    [global::ProtoBuf.ProtoMember(6, IsRequired = true, Name=@"map_theme", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int map_theme
    {
      get { return _map_theme; }
      set { _map_theme = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"map_data1")]
  public partial class map_data1 : global::ProtoBuf.IExtensible
  {
    public map_data1() {}
    
    private int _map_ver;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"map_ver", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int map_ver
    {
      get { return _map_ver; }
      set { _map_ver = value; }
    }
    private int _mode;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"mode", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int mode
    {
      get { return _mode; }
      set { _mode = value; }
    }
    private int _time;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"time", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int time
    {
      get { return _time; }
      set { _time = value; }
    }
    private int _no_music;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"no_music", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int no_music
    {
      get { return _no_music; }
      set { _no_music = value; }
    }
    private int _end_area;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"end_area", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int end_area
    {
      get { return _end_area; }
      set { _end_area = value; }
    }
    private readonly global::System.Collections.Generic.List<protocol.map.map_data_sub> _maps = new global::System.Collections.Generic.List<protocol.map.map_data_sub>();
    [global::ProtoBuf.ProtoMember(6, Name=@"maps", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<protocol.map.map_data_sub> maps
    {
      get { return _maps; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}